# Generated by Django 6.0.1 on 2026-01-26 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='زمان تخمینی بر حسب دقیقه', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='زمان تخمینی (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=80, verbose_name='عنوان'),
        ),
    ]
